import { TelegramFile, StorageStats } from '../types';

export const DEMO_FILES: TelegramFile[] = [
  {
    id: 101,
    filename: 'Nature_Cinematic_4K.mp4',
    caption: 'Nature landscape 4K sample video for testing in-app media player and streaming',
    mimeType: 'video/mp4',
    size: 48500000, // 48.5 MB
    category: 'videos',
    hasThumb: true,
    date: Date.now() - 3600000 * 4,
    duration: 596,
    width: 1920,
    height: 1080,
    directUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 102,
    filename: 'Project_Architecture_Blueprint_2026.pdf',
    caption: 'Full system specifications and database design docs',
    mimeType: 'application/pdf',
    size: 4200000,
    category: 'documents',
    hasThumb: true,
    date: Date.now() - 3600000 * 12,
    directUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloadUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnailUrl: null,
  },
  {
    id: 103,
    filename: 'Sunset_Alps_Panorama.jpg',
    caption: 'Mountain peak photography at golden hour',
    mimeType: 'image/jpeg',
    size: 6800000,
    category: 'images',
    hasThumb: true,
    date: Date.now() - 3600000 * 24,
    width: 3840,
    height: 2160,
    directUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&auto=format&fit=crop&q=80',
    downloadUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 104,
    filename: 'Lofi_Chill_Ambient_Vibes.mp3',
    caption: 'Relaxing study beats & melodic synth track',
    mimeType: 'audio/mpeg',
    size: 9400000,
    category: 'audio',
    hasThumb: true,
    date: Date.now() - 3600000 * 36,
    duration: 372,
    directUrl: 'https://cdn.freesound.org/previews/612/612081_5674468-lq.mp3',
    downloadUrl: 'https://cdn.freesound.org/previews/612/612081_5674468-lq.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 105,
    filename: 'TeleCloud_Source_Release_v1.0.zip',
    caption: 'Clean compiled distribution package for deployment',
    mimeType: 'application/zip',
    size: 28500000,
    category: 'archives',
    hasThumb: false,
    date: Date.now() - 3600000 * 48,
    directUrl: '#',
    downloadUrl: '#',
    thumbnailUrl: null,
  },
  {
    id: 106,
    filename: 'Cyberpunk_Neon_City.png',
    caption: 'Futuristic Tokyo neon aesthetics illustration',
    mimeType: 'image/png',
    size: 12200000,
    category: 'images',
    hasThumb: true,
    date: Date.now() - 3600000 * 60,
    width: 2560,
    height: 1440,
    directUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1600&auto=format&fit=crop&q=80',
    downloadUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 107,
    filename: 'Database_Backup_Postgres_2026.sql.gz',
    caption: 'Encrypted weekly backup dump archive',
    mimeType: 'application/gzip',
    size: 89000000,
    category: 'archives',
    hasThumb: false,
    date: Date.now() - 3600000 * 72,
    directUrl: '#',
    downloadUrl: '#',
    thumbnailUrl: null,
  },
  {
    id: 108,
    filename: 'Deep_Focus_Podcast_Ep42.mp3',
    caption: 'Tech insights on cloud architectures and MTProto protocols',
    mimeType: 'audio/mpeg',
    size: 34100000,
    category: 'audio',
    hasThumb: true,
    date: Date.now() - 3600000 * 96,
    duration: 180,
    directUrl: 'https://cdn.freesound.org/previews/573/573381_11861866-lq.mp3',
    downloadUrl: 'https://cdn.freesound.org/previews/573/573381_11861866-lq.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&auto=format&fit=crop&q=80',
  },
];

export const DEMO_STATS: StorageStats = {
  totalFiles: DEMO_FILES.length,
  totalSize: DEMO_FILES.reduce((acc, f) => acc + f.size, 0),
  categories: {
    images: {
      count: DEMO_FILES.filter(f => f.category === 'images').length,
      size: DEMO_FILES.filter(f => f.category === 'images').reduce((acc, f) => acc + f.size, 0),
    },
    videos: {
      count: DEMO_FILES.filter(f => f.category === 'videos').length,
      size: DEMO_FILES.filter(f => f.category === 'videos').reduce((acc, f) => acc + f.size, 0),
    },
    audio: {
      count: DEMO_FILES.filter(f => f.category === 'audio').length,
      size: DEMO_FILES.filter(f => f.category === 'audio').reduce((acc, f) => acc + f.size, 0),
    },
    documents: {
      count: DEMO_FILES.filter(f => f.category === 'documents').length,
      size: DEMO_FILES.filter(f => f.category === 'documents').reduce((acc, f) => acc + f.size, 0),
    },
    archives: {
      count: DEMO_FILES.filter(f => f.category === 'archives').length,
      size: DEMO_FILES.filter(f => f.category === 'archives').reduce((acc, f) => acc + f.size, 0),
    },
    other: {
      count: DEMO_FILES.filter(f => f.category === 'other').length,
      size: DEMO_FILES.filter(f => f.category === 'other').reduce((acc, f) => acc + f.size, 0),
    },
  },
};
